kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    dry_run: true
    repo: peterhack/aws-demo
  when:
    event:
    - pull_request
    - push

- name: push
  image: plugins/docker
  settings:
    username: peterhack
    password: 
      from_secret: dockerhubpw
    repo: peterhack/aws-demo
    tag:
    - latest
    - ${DOCKER_TAG}
  when:
    event:
    - custom
